import _ from 'lodash'
import glob from 'glob'
import fs from 'fs'
import path from 'path'
import { source } from 'common-tags'

import {
  LIB_DIR,
  PAGES_DIR
} from '../../../config'

import { dev } from 'lib/utils/env'

const PAGES_INDEX_TEMPLATE_FILE = path.resolve(LIB_DIR, './page.js')
const PAGES_INDEX_FILE = path.resolve(PAGES_DIR, './index.js')

if (dev) {
  // Watch for /pages changes.
  const watcher = require('sane')(PAGES_DIR, { ignored: ['./index.js'] })

  const onChange = () => {
    console.log('Detect changes at /pages')
    syncPages()
  }

  watcher.on('ready', () => {
    watcher.on('add', onChange)
    watcher.on('delete', onChange)
  })
}

// Find page-components from `/pages`
export const fetchPages = () => {
  // Find directories from `/pages`
  const directories = _.map(glob.sync('**/', { cwd: PAGES_DIR }), (dir) => _.trimEnd(dir, '/'))

  // Find files from `/pages`
  const files = _.map(glob.sync('**/*.js', {
    cwd: PAGES_DIR,
    ignore: ['**/_*.js', '**/index.js']
  }), (file) => _.trimEnd(file, '.js'))

  // Concat and normalize as path (eg: `/foo`)
  return _.map([...files, ...directories], (page) => `/${_.toLower(page)}`)
}

// Inject found pages into `/pages/index.js`
export const syncPages = () => {
  let template = fs.readFileSync(PAGES_INDEX_TEMPLATE_FILE, 'utf8')

  const pages = fetchPages()

  // const defs = _.map(pages, (page) => (
  //   `const ${getPageName(page)} = loadable(createLoadable(import('.${page}')), { render: renderLoadable })`
    // `const ${getPageName(page)} = loadable(async () => delay(import('.${page}')), { render: renderLoadable })`
  // )).join('\n')

  const Pages = source`
    export const Pages = {
      ${_.map(pages, (page) => (source`
        '${page}': loadable(async () => delay(import('.${page}')), { render: renderLoadable })
      `)).join(',\n')}
    }`

  template = template.replace(/export const Pages = \[]/g, `${Pages}`)

  // Add Banner to source.
  template = source`
    // ==============================
    // THIS FILE IS AUTOMATICALLY GENERATED BY APP.
    // DO NOT EDIT THIS FILE DIRECTLY.
    // SEE: \`/server/utils/syncPages.js\`
    // ==============================    
  ` + '\n\n' + template

  fs.writeFileSync(PAGES_INDEX_FILE, template, { encoding: 'utf8' })

  console.log('pages = ', pages)
}

export default syncPages
